[build-system]
requires = [
  "setuptools==83.0.0",
  "wheel==0.47.0",
  "setuptools-git-versioning==3.1.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
mfai = "mfai"

[tool.setuptools-git-versioning]
enabled = true

[tool.setuptools.package-data]
mfai = [
  # Include tiktoken cache files
  "tokenizers/tiktoken_cache/6c7ea1a7e38e3a7f062df639a5b80947f075ffe6",
  "tokenizers/tiktoken_cache/6d1cbeee0f20b3d9449abfede4726ed8212e3aee",

  # Include marker file `py.typed` to respect PEP561 and declare this package as type hinted
  "py.typed",

  # include Qwen3.5 tokenizer file
  "tokenizers/qwen3.5/tokenizer.json",
]

[project]
name = "mfai"
authors = [
  { name = "Frank Guibert", email = "frank.guibert@meteo.fr" },
  { name = "Theo Tournier", email = "theo.tournier@meteo.fr" },
  { name = "Lea Berthomier", email = "lea.berthomier@meteo.fr" },
  { name = "Bruno Pradel", email = "bruno.pradel@meteo.fr" },
  { name = "Oscar Dewasmes", email = "oscar.dewasmes@meteo.fr" },
]
description = "Meteo-France's Artificial Intelligence Python Package"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
]
dynamic = ["version"]
license-files = ["LICENSE"]
keywords = [
  "PyTorch",
  "Deep Learning",
  "Artificial Intelligence",
  "Meteo-France",
]
dependencies = [
  "dataclasses-json>=0.6",
  "einops>=0.8",
  "lightning[pytorch-extra]",
  "onnx>=1.17.0",
  "onnxruntime>=1.20,<1.24 ; python_version < '3.11'",
  "onnxruntime>=1.20 ; python_version >= '3.11'",
  "onnxscript>=0.1",
  "torch>=2.5,<3",
  "torchvision>=0.19",
  "tabulate>=0.9",
  "torchmetrics>=1.6",
]

[project.optional-dependencies]
llm = [
  # Tokenizers, GPT2, Llama2, Llama3, Fuyu, Qwen
  "huggingface_hub>=0.26",
  "sentencepiece>=0.2",
  "tiktoken>=0.8",
  "tokenizers>=0.22",
]
weather_forecast = [
  # Nlam, pangu and archesweather models
  "timm>=1.0",
  "scipy>=1.14",
  "torch-geometric>=2.6",
  "axial-attention>=0.6.1",
]
vision_transformers = [
  # Swinunetr and UnetrPP models
  "monai>=1.5",
]
docs = [
  "sphinx>=7.0.0",
  "furo",
  "sphinx-autodoc-typehints",
  "myst-parser",
  "ghp-import",
  "sphinxcontrib-mermaid",
]
dev = [
  "pytest==9.1.1",
  "pytest-cov==7.1.0",
  "ruff==0.15.20",
  "pyright[nodejs]==1.1.411",
]

[project.urls]
Homepage = "https://github.com/meteofrance/mfai"

[tool.uv]
# Enforces the use of prebuilt binary wheels over source distributions
# that require a build step and executes arbitrary code when installing.
pip.only-binary = [":all:"]
exclude-newer = "15 days"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
target-version = "py312"
line-length = 88
builtins = ["_"]
include = ["mfai/**/*.py", "exemples/**/*.py", "tests/**/*.py", "doc/**/*.py", "scripts/**/*.py"]
exclude = []

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
  "I", # I = isort
  "F", # pyflakes
  "W", # pycodestyle warnings
  "E", # pycodestyle errors
  "D", # pydocstyle
]
ignore = [
  "D100", # Allow undocumented-public-module
  "D200", # Allow unnecessayry-multiline-docstring
  "D202", # Allow blank-line-after-function after function docstring
  "D203", # Allow incorrect-blank-line-before-class
  "D205", # Allow missing-blank-line-after-summary
  "D212", # Allow multi-line-summary-first-line
  "D213", # Allow multi-line-summary-second-line
  "D415", # Allow missing-terminal-punctuation

  "D101", # Allow undocumented-public-class
  "D102", # Allow undocumented-public-method
  "D103", # Allow undocumented-public-function
  "D104", # Allow undocumented-public-package
  "D105", # Allow undocumented-magic-method
  "D107", # Allow undocumented-public-init
  "E501", # Allow line too long
]

[tool.ruff.lint.pydocstyle]
convention = "google"
# ignore-var-parameters = true

[tool.ruff.lint.pycodestyle]
max-line-length = 88
ignore-overlong-task-comments = true

[tool.ruff.lint.flake8-unused-arguments]
ignore-variadic-names = true


[tool.coverage.run]
source = ["`mfai/"]
omit = []
fail_under = 85

[tool.coverage.report]
show_missing = true
exclude_also = ['def __repr__', 'if __name__ == .__main__.:']

[tool.pyright]
# https://microsoft.github.io/pyright/#/configuration?id=sample-pyprojecttoml-file

## Run options
include = ["mfai", "scripts", "tests"]
ignore = []

verboseOutput = true

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonVersion = "3.12"
pythonPlatform = "Linux"

useLibraryCodeForTypes = true

## Type hinting options
# Disallow list[Any] and set[any], forces to fully type them.
strictListInference = true
strictSetInference = true
# Allow dict[Any] as complex dict structures make typing irelevant.
strictDictionaryInference = false

# Analyse everything
analyzeUnannotatedFunctions = true

# Allow implicit optional in function parameter definition.
# def foo(param: int = None) -> None:
strictParameterNoneValue = false

enableTypeIgnoreComments = true # Allows  # type: ignore

deprecateTypingAliases = true # Deprecates the use of typing.List, Dict, ...

## Type checking rules
# When a class @property getter and setter have different types.
reportPropertyTypeMismatch = "error"

# Cyclical import chains slow down type analysis and hint at architectural layering issues.
reportImportCycles = "error"

reportUnusedImport = "error"

reportDuplicateImport = "error"

reportWildcardImportFromLibrary = "error"

reportUntypedFunctionDecorator = "error"

reportUntypedClassDecorator = "error"

reportUntypedBaseClass = "error"

reportUntypedNamedTuple = "error"

reportPrivateUsage = "error"

reportTypeCommentUsage = "error"

reportPrivateImportUsage = "error"

reportConstantRedefinition = "error"

# reportDeprecated [boolean or string, optional]: Generate or suppress diagnostics for use of a class or function that has been marked as deprecated. The default value for this setting is "none".

reportInconsistentConstructor = "error"

reportUninitializedInstanceVariable = "error"

# Disallow input or return parameters for functions or methods that have an unknown type
reportUnknownParameterType = "none"
reportUnknownArgumentType = "none"
reportUnknownLambdaType = "none"
reportUnknownVariableType = "none"
reportUnknownMemberType = "none"

reportMissingParameterType = "error"
reportMissingTypeArgument = "none"

reportCallInDefaultInitializer = "none"

reportUnnecessaryIsInstance = "error"
reportUnnecessaryCast = "error"
reportUnnecessaryComparison = "error"
reportUnnecessaryContains = "error"
reportAssertAlwaysTrue = "error"
reportImplicitStringConcatenation = "none"

reportUnusedExpression = "error"

reportUnnecessaryTypeIgnoreComment = "error"

reportMatchNotExhaustive = "error"

reportUnreachable = "error"

reportImplicitOverride = "error"