name: GPT2 weights download script

on:
  push:
    branches: [ "main" ]
    paths:
      - 'scripts/gpt2_weights_download/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'scripts/gpt2_weights_download/**'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Gather changed files
      id: changed-files
      uses: tj-actions/changed-files@v47
      with:
        files: |
          scripts/gpt2_weights_download/**

    - name: Lint with ruff
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        pip install ruff==0.15.9
        ruff format --check ${{ steps.changed-files.outputs.all_changed_files }}
        ruff check ${{ steps.changed-files.outputs.all_changed_files }}

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts/gpt2_weights_download

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Sync dependencies
      run: uv sync --locked --dev

    - name: Test with pytest
      run: uv run pytest
