# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    env:
      PYTHONPATH: '.'
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Gather Python changed files
      id: changed-py-files
      uses: tj-actions/changed-files@7dee1b0c1557f278e5c7dc244927139d78c0e22a # v47.0.4
      with:
        files: |
          *.py
          **/*.py

    - name: Lint with ruff
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: |
        pip install ruff
        ruff format --check ${{ steps.changed-py-files.outputs.all_changed_files }}
        ruff check ${{ steps.changed-py-files.outputs.all_changed_files }}

  tests:
    env:
      PYTHONPATH: '.'
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim

    steps:
    - uses: actions/checkout@v4

    - name: Check disk space
      run: df . -h

    - name: Gather Python changed files
      id: changed-py-files
      uses: tj-actions/changed-files@7dee1b0c1557f278e5c7dc244927139d78c0e22a # v47.0.4
      with:
        files: |
          *.py
          **/*.py

    - name: Install dependencies
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: |
        pip install --upgrade pip
        pip install .[llm,dev]

    - name: Type hinting with mypy on changed files
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: |
        mypy ${{ steps.changed-py-files.outputs.all_changed_files }}

    - name: Test with pytest
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: |
        pytest --cov=mfai --cov-fail-under=85 tests/